title: Apparatus
description: "Website about Apparatus"
url: https://apparatus.voxelmanip.se

baseurl: /

lang: en_GB

exclude:
  - README.md

permalink: pretty

sass:
  style: compressed
  sourcemap: never

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
